### YamlMime:ManagedReference
items:
- uid: Heir.Runtime.Values
  commentId: N:Heir.Runtime.Values
  id: Heir.Runtime.Values
  children:
  - Heir.Runtime.Values.FunctionValue
  - Heir.Runtime.Values.IValue
  - Heir.Runtime.Values.ObjectValue
  langs:
  - csharp
  - vb
  name: Heir.Runtime.Values
  nameWithType: Heir.Runtime.Values
  fullName: Heir.Runtime.Values
  type: Namespace
  assemblies:
  - Heir
references:
- uid: Heir.Runtime.Values.FunctionValue
  commentId: T:Heir.Runtime.Values.FunctionValue
  href: Heir.Runtime.Values.FunctionValue.html
  name: FunctionValue
  nameWithType: FunctionValue
  fullName: Heir.Runtime.Values.FunctionValue
- uid: Heir.Runtime.Values.IValue
  commentId: T:Heir.Runtime.Values.IValue
  parent: Heir.Runtime.Values
  href: Heir.Runtime.Values.IValue.html
  name: IValue
  nameWithType: IValue
  fullName: Heir.Runtime.Values.IValue
- uid: Heir.Runtime.Values.ObjectValue
  commentId: T:Heir.Runtime.Values.ObjectValue
  href: Heir.Runtime.Values.ObjectValue.html
  name: ObjectValue
  nameWithType: ObjectValue
  fullName: Heir.Runtime.Values.ObjectValue
- uid: Heir.Runtime.Values
  commentId: N:Heir.Runtime.Values
  href: Heir.html
  name: Heir.Runtime.Values
  nameWithType: Heir.Runtime.Values
  fullName: Heir.Runtime.Values
  spec.csharp:
  - uid: Heir
    name: Heir
    href: Heir.html
  - name: .
  - uid: Heir.Runtime
    name: Runtime
    href: Heir.Runtime.html
  - name: .
  - uid: Heir.Runtime.Values
    name: Values
    href: Heir.Runtime.Values.html
  spec.vb:
  - uid: Heir
    name: Heir
    href: Heir.html
  - name: .
  - uid: Heir.Runtime
    name: Runtime
    href: Heir.Runtime.html
  - name: .
  - uid: Heir.Runtime.Values
    name: Values
    href: Heir.Runtime.Values.html
