### YamlMime:ManagedReference
items:
- uid: Heir.Runtime.Values.IValue
  commentId: T:Heir.Runtime.Values.IValue
  id: IValue
  parent: Heir.Runtime.Values
  children: []
  langs:
  - csharp
  - vb
  name: IValue
  nameWithType: IValue
  fullName: Heir.Runtime.Values.IValue
  type: Interface
  source:
    remote:
      path: Heir/Runtime/Values/IValue.cs
      branch: master
      repo: git@github.com:heir-lang/heir.git
    id: IValue
    path: Heir/Runtime/Values/IValue.cs
    startLine: 2
  assemblies:
  - Heir
  namespace: Heir.Runtime.Values
  syntax:
    content: public interface IValue
    content.vb: Public Interface IValue
references:
- uid: Heir.Runtime.Values
  commentId: N:Heir.Runtime.Values
  href: Heir.html
  name: Heir.Runtime.Values
  nameWithType: Heir.Runtime.Values
  fullName: Heir.Runtime.Values
  spec.csharp:
  - uid: Heir
    name: Heir
    href: Heir.html
  - name: .
  - uid: Heir.Runtime
    name: Runtime
    href: Heir.Runtime.html
  - name: .
  - uid: Heir.Runtime.Values
    name: Values
    href: Heir.Runtime.Values.html
  spec.vb:
  - uid: Heir
    name: Heir
    href: Heir.html
  - name: .
  - uid: Heir.Runtime
    name: Runtime
    href: Heir.Runtime.html
  - name: .
  - uid: Heir.Runtime.Values
    name: Values
    href: Heir.Runtime.Values.html
